apiVersion: batch/v1
kind: Job
metadata:
  name: calcuag-job
spec:
  template:
    spec:
      containers:
      - name: calcuag-job
        image: yash5090/calcuag:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
